In [1]:
import numpy as np

# Boolean  indexing

# Array indexing for changing

In [2]:
# create a 3x2 array
an_array = np.array([[11,12],[21,22],[31,32]])
print(an_array)


[[11 12]
 [21 22]
 [31 32]]


In [3]:
# create a filter which will be boolean value for whether each element
# meets this
filter = (an_array > 15)
filter

array([[False, False],
       [ True,  True],
       [ True,  True]])

notice that filter is a same size ndarray as an array which filled with True for each elemenr whose corresponding element in an_array which is greater than 15 and False for those element whose value are less than 15 

In [4]:
# we  can now select just those element which meet that criterea
print(an_array[filter])

[21 22 31 32]


In [5]:
# for short ,we could have used the approch below without the need for the above
an_array[an_array > 15] 
an_array[(an_array > 20) &(an_array < 30)]
an_array[(an_array % 2 == 0)]

array([12, 22, 32])

what is actualy useful is that we can actualy change elements in the same array applying a similar logical filter .lets add 1000 to all the even values

In [6]:
an_array[(an_array % 2 == 0)] += 100
print(an_array)

[[ 11 112]
 [ 21 122]
 [ 31 132]]


# Datatypes and Array Operation

Datatypes

In [7]:
ex1 = np.array([11,12])  # python assign the data type
print(ex1.dtype)

int32


In [8]:
ex2= np.array([11.0,12.0])
print(ex2.dtype)

float64


In [9]:
ex3= np.array([11,21], dtype=np.int64)
print(ex3.dtype)

int64


In [10]:
# you can use to force float into intger(using floor function)
ex4 = np.array([11.1,12.7],dtype =np.int64)
print(ex4.dtype)
print()
print(ex4)

int64

[11 12]


In [11]:
# you can use this to forcr intger into float to anticipate
# the value may change to float later
ex5 = np.array([11,12],dtype =np.float64)
print(ex5.dtype)
print()
print(ex5)


float64

[11. 12.]


# Arithmetic Array Operation

In [12]:
x = np.array([[111,112],[121,122]], dtype =np.int)
y= np.array([[211.1,212.1],[221.1,222.1]], dtype =np.float64)
print(x)
print()
print(y)

[[111 112]
 [121 122]]

[[211.1 212.1]
 [221.1 222.1]]


In [13]:
# add
print(x + y)
print()
print(np.add(x,y))

[[322.1 324.1]
 [342.1 344.1]]

[[322.1 324.1]
 [342.1 344.1]]


In [14]:
# subtract
print(x - y)
print()
print(np.subtract(x,y))

[[-100.1 -100.1]
 [-100.1 -100.1]]

[[-100.1 -100.1]
 [-100.1 -100.1]]


In [15]:
# multiply
print(x *y)
print()
print(np.multiply(x,y))

[[23432.1 23755.2]
 [26753.1 27096.2]]

[[23432.1 23755.2]
 [26753.1 27096.2]]


In [16]:
# division
print(x/y)
print()
print(np.divide(x,y))

[[0.52581715 0.52805281]
 [0.54726368 0.54930212]]

[[0.52581715 0.52805281]
 [0.54726368 0.54930212]]


In [17]:
# square root
print(np.sqrt(x))

[[10.53565375 10.58300524]
 [11.         11.04536102]]


In [18]:
# exponent (e**x)
print(np.exp(x))

[[1.60948707e+48 4.37503945e+48]
 [3.54513118e+52 9.63666567e+52]]


# Stastical,Sorting and Set Operation

In [19]:
# <p style = "font-family: Arial; font-size: 1.75em;  color: #2462c0; font-style:bold">
# <br>
# Basic Stastical Operation
# </p>

In [20]:
# set up a random 2x4 matrix
arr = 10* np.random.randn(2,5)
print(arr)

[[ -3.63185037   6.10900958 -21.13038796   8.81918624 -21.55371475]
 [-11.49110494 -14.34680565  -9.01653602   3.08919538  -1.78133881]]


In [21]:
# compute the mean for all elements
print(arr.mean())

-6.4934347305407965


In [22]:
# compute the means by the row
print(arr.mean(axis = 1))

[-6.27755145 -6.70931801]


In [23]:
# compute the mean by colomun
print(arr.mean(axis = 0))

[ -7.56147766  -4.11889803 -15.07346199   5.95419081 -11.66752678]


In [24]:
# sum all the element
print(arr.sum())

-64.93434730540797


In [25]:
# computing the medians
print(np.median(arr, axis = 1))

[-3.63185037 -9.01653602]


# Sorting

In [26]:
# crearte a 10 element od randoms
unsorted = np.random.randn(10)
print(unsorted)

[-1.40259914  0.38758741 -0.01433771 -0.36271752 -0.3391622   0.52728259
 -1.55190866 -0.80829072  0.46295483  0.22001769]


In [27]:
# create a copy and sort
sorted = np.array(unsorted)
sorted.sort()
print(sorted)
print()
print(unsorted)

[-1.55190866 -1.40259914 -0.80829072 -0.36271752 -0.3391622  -0.01433771
  0.22001769  0.38758741  0.46295483  0.52728259]

[-1.40259914  0.38758741 -0.01433771 -0.36271752 -0.3391622   0.52728259
 -1.55190866 -0.80829072  0.46295483  0.22001769]


In [28]:
# inplace sorting
unsorted.sort()
print(unsorted)

[-1.55190866 -1.40259914 -0.80829072 -0.36271752 -0.3391622  -0.01433771
  0.22001769  0.38758741  0.46295483  0.52728259]


# Finding Unique elements:

In [29]:
array = np.array([1,2,1,4,2,1,4,2])
print(np.unique(array))

[1 2 4]


# Set Operation With np.array data type

In [30]:
s1 = np.array(["desk","chair","bulb"])
s2 = np.array(["lamp","bulb","chair"])
print(s1,s2)

['desk' 'chair' 'bulb'] ['lamp' 'bulb' 'chair']


In [31]:
print(np.intersect1d(s1,s2))

['bulb' 'chair']


In [32]:
print(np.union1d(s1,s2))

['bulb' 'chair' 'desk' 'lamp']


In [33]:
print(np.setdiff1d(s1,s2)) # element in set s1 that not in s2

['desk']


In [34]:
print(np.in1d(s1,s1)) # which element of s1 is also in s2

[ True  True  True]


# Numpy ,Broadcasting

# Broadcasting:

Introduction to broascasting 

In [72]:
start = np.zeros((4,3))
print(start)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [74]:
# create a rank 1 ndarray with 3 values
add_row = np.array([1,0,2])
print(add_row)

[1 0 2]


In [76]:
y = start + add_row # add to each row of "start" using broascating
print(y)

[[1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]]


In [80]:
# create an ndarray which is 4 x 1 to broascasting accross column
add_cols = np.array([[0,1,2,3]])
add_cols = add_cols.T # T is denoted from transpose
print(add_cols)

[[0]
 [1]
 [2]
 [3]]


In [81]:
# add to each column of "start" using broadcasting
y = start + add_cols
print(y)

[[0. 0. 0.]
 [1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


In [82]:
# thiss will just broascasting in both dimension
add_scalar = np.array([1])
print(start + add_scalar)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


Example from the slides

In [85]:
# create our 3 x 4 matrix
arrA = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arrA)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


# Speedtest: ndarray vs list

first setup parameter for speed test . We will be testing to sum in an ndarray versus a list


In [88]:
from numpy import arange
from timeit import Timer

size = 1000000
timeits =1000

In [89]:
# create  the ndarray with values 0,1,2.... size-1
nd_array = arange(size)
print(type(nd_array))

<class 'numpy.ndarray'>


In [90]:
# timer expect the operation as a parameter,
# here we pass nd_array.sum()
timer_numpy = Timer("nd_array.sum()","from __main__ import nd_array")
print("Time taken by numpy ndarray: %f seconds" %(timer_numpy.timeit(timeits)/(timeits)))

Time taken by numpy ndarray: 0.000865 seconds


In [91]:
# create the list with values 1,2,3
a_list = list(range(size))
print(a_list)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [96]:
# timer expect the operation as a parameter here we pass sum(a_list)
timer_list = Timer("sum(a_list)","from __main__ import a_list")
print("time taken by list: %f seconds" %(timer_list.timeit(timeits)/(timeits)))

time taken by list: 0.084365 seconds
