# Getting started with ndarray

In [2]:
import numpy as np

an_array = np.array([3,33,333])    
print(type(an_array))


<class 'numpy.ndarray'>


In [3]:
# test the shape of the arrray
print(an_array.shape)

(3,)


In [4]:
# because this is a 1 rank array
print(an_array[0],an_array[1],an_array[2])

3 33 333


In [5]:
an_array[0]= 888
print(an_array)

[888  33 333]


# How to create rank 2 numpy

In [11]:
another= np.array([[11,12,13],[21,22,23]])
print(another)
print("The shape is 2 rows,3 columns:",another.shape)
print("Accessing element [0,0],[0,1] and [1,0] of the ndarray: ", another[0,0],another[0,1],another[1,0])

[[11 12 13]
 [21 22 23]]
The shape is 2 rows,3 columns: (2, 3)
Accessing element [0,0],[0,1] and [1,0] of the ndarray:  11 12 21


In [13]:
import numpy as np
# create a 2x2 array of zeros
ex1 = np.zeros((2,2))
print(ex1)

[[0. 0.]
 [0. 0.]]


In [16]:
# creating a 2x2 array filled with 9.0
ex2 = np.full((2,2),9.0)
print(ex2)

[[9. 9.]
 [9. 9.]]


In [15]:
# creating a 2x2 array matrix with the digonal is and other 0
ex3= np.eye(2,2)
print(ex3)

[[1. 0.]
 [0. 1.]]


In [17]:
# creating of an array of one
ex4 = np.ones((1,2))
print(ex4)

[[1. 1.]]


In [20]:
# notice that the anve ndarray (ex4) is actualy rank 2,it is a 2x1 array
print(ex4.shape)
# which means we need to use two indexes to access an element
print()
print(ex4[0,1])

(1, 2)

1.0


In [21]:
# create a random array between 1 and 2
ex5 = np.random.random((2,2))
print(ex5)

[[0.4074697  0.50125887]
 [0.32216945 0.95150332]]


# indexing 

# Slice indexing

In [22]:
import numpy as np
# rank 2 array of shape (3,4)
an_array = np.array([[11,12,13,14],[21,22,23,24],[31,32,33,34]])
print(an_array)


[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


use array slicing to get a subarray consist of the first 2 rows x 2 column

In [23]:
a_slice = an_array[:2,1:3]
print(a_slice)

[[12 13]
 [22 23]]


when you modify a slice actualy the underling array

In [25]:
print("Before:",an_array[0,1])
a_slice[0,0] = 1000  # a_slicce[0,0] is the same piece of data as an_arrayy[0,1]
print("After:",an_array[0,1])

Before: 1000
After: 1000


In [31]:
import numpy as np
# rank 2 array of shape (3,4)
an_array = np.array([[11,12,13,14],[21,22,23,24],[31,32,33,34]])
print(an_array)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [36]:
# using both integer indexing and slicing generate an array of lower rank
row_rank1 = an_array[1, :]
print(row_rank1, row_rank1.shape)

[21 22 23 24] (4,)


In [34]:
# slicing alone : generate an array of the same rank as the an_array
row_rank2 = an_array[1:2, :]
print(row_rank2,row_rank2.shape)

[[21 22 23 24]] (1, 4)


In [40]:
# we can do the same for the columun of an array
print()
col_rank1 = an_array[:, 1]
col_rank2 =an_array[:, 1:2]



print(col_rank1,col_rank1.shape)
print
print(col_rank2,col_rank2.shape)


[12 22 32] (3,)
[[12]
 [22]
 [32]] (3, 1)
