In [1]:
import numpy as np

# The Basics

In [13]:
a = np.array([1,2,3], dtype = "int16")
print(a)

[1 2 3]


In [14]:
b = np.array([[9,8,7],[6,5,4]])
print(b)

[[9 8 7]
 [6 5 4]]


In [15]:
# get dimention
a.ndim
print()
b.ndim

2

In [16]:
# get shape
a.shape

(3,)

In [17]:
b.shape

(2, 3)

In [18]:
# get size
a.itemsize

2

In [22]:
# get total size
a.nbytes
# or
a.size*a.itemsize

6

# Accessing/Changing specific elements,rows ,columns,etc

In [23]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [24]:
# get a specific element[r,c]
a[1,5]

13

In [25]:
# get specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [26]:
# get specific columun
a[:,2]

array([ 3, 10])

In [31]:
# getting a little more fancy[startindex:endindex:stepsize]
# a[0,1:6:2] or
a[0,1:-1:2]


array([2, 4, 6])

In [35]:
a[1,5]= 20

a[:,2]= 5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [36]:
a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


3-example

In [46]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [47]:
# get specific element(work outside in)
# b[0,1,1] or
# b[:,1,:2] or
b[:,0,:]


array([[1, 2],
       [5, 6]])

In [50]:
# replace
b[:,1,:] = [[9,9],[8,8]]
print(b)



[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


# Initializing Different Types of Array

In [55]:
# all 0s matrix
# np.zeros((2,3,3,2))
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [62]:
# all 1st  matrix
np.ones((4,2,2,),dtype = "int32")

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [63]:
# Any other number
np.full((2,2),99, dtype ="float32")

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [64]:
# Any other number(full_like)
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [69]:
# Random decimal numbers
np.random.rand(4,2,3)

array([[[0.61456995, 0.05841099, 0.8443428 ],
        [0.33649605, 0.93869641, 0.14846232]],

       [[0.20443965, 0.80992678, 0.085496  ],
        [0.4254723 , 0.95411962, 0.54435727]],

       [[0.24465493, 0.69473189, 0.63231483],
        [0.56720766, 0.92016987, 0.0332774 ]],

       [[0.33615537, 0.28400235, 0.75375238],
        [0.98578272, 0.32469462, 0.6202423 ]]])

In [71]:
np.random.rand(4,2)

array([[0.42933369, 0.39489803],
       [0.70377323, 0.62391527],
       [0.19351274, 0.61041496],
       [0.63145413, 0.28214341]])

In [70]:
# or
np.random.random_sample(a.shape)

array([[0.55109906, 0.15639068, 0.65286611, 0.19721286, 0.07961015,
        0.49164963, 0.67404521],
       [0.3763102 , 0.81342901, 0.46311719, 0.29252204, 0.21959398,
        0.77213989, 0.17454607]])

In [72]:
# random integer value
np.random.randint(-4,8,size =(3,3))

array([[ 3, -2, -2],
       [ 5,  4,  2],
       [-1,  1, -4]])

### Solving the problem

In [73]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [80]:
# Repeat an array
# arr = np.array([1,2,3]) or 2 dimentional
arr = np.array([[1,2,3]])
r1 =np.repeat(arr,3,axis = 0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [91]:
output = np.ones((5,5))
print(output)
z = np.zeros((3,3))
z[1,1] = 9
print(z)
output[1:4,1:4] = z
print(output)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### Becareful when copying arrays

In [97]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(a)

[1 2 3]


## Mathematics with numpy

In [98]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [99]:
a + 2

array([3, 4, 5, 6])

In [100]:
a-2

array([-1,  0,  1,  2])

In [101]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [102]:
a*2

array([2, 4, 6, 8])

In [103]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [104]:
a**2

array([ 1,  4,  9, 16], dtype=int32)

In [105]:
# Take sin of a
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [106]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [81]:

np.array([5,5])

array([5, 5])

In [118]:
# for more reference (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

### Linear Algebra

In [114]:
a = np.ones((2,3))
print(a)
b = np.full((3,2),2)
print(b)
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [117]:
# Finding the determinant
c = np.identity(3)
c
np.linalg.det(c)


1.0

In [119]:
# For more reference (https://docs.scipy.org/doc/numpy/reference/routines.math.html)
# Determinat
# Trace
# Singlar vector Decomposion
# Eingenvalues
# Matrix Norm
# Inverse

### Stastics

In [121]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [122]:
np.min(stats)

1

In [123]:
np.max(stats,axis = 1)

array([3, 6])

In [124]:
np.sum(stats)

21

In [125]:
np.sum(stats, axis = 0)

array([5, 7, 9])

#### Recognizing Array

In [131]:
before= np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((2,2,2))

[[1 2 3 4]
 [5 6 7 8]]


In [132]:
print(after)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [133]:
# Vertical stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [134]:
# Horizontal stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
h2

array([[0., 0.],
       [0., 0.]])

In [137]:
np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Miscellaneous

##### load data from file

In [148]:
filedata = np.genfromtxt("data.txt", delimiter = ",")
filedata.astype("int32")
filedata

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

### Boolean Masking and Advanced Indexing

In [149]:
filedata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [150]:
filedata[filedata > 50]

array([196.,  75., 766.,  75.,  55., 999.,  78.,  76.,  88.])

In [151]:
# index with a list in NumPY
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [152]:
np.any(filedata > 50, axis = 0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [153]:
np.all(filedata > 50 , axis =0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [154]:
np.all(filedata > 50 , axis =1)

array([False, False, False])

In [155]:
((filedata > 50) & (filedata < 100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [157]:
(~((filedata > 50) & (filedata < 100)))
# not

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])